services:
  - type: web
    name: introhater
    env: node
    plan: free
    buildCommand: "npm install && npm test"
    dockerFilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: RPDB_KEY
        sync: false
    autoDeploy: true
